apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperion-proxy
  namespace: hyperion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperion-proxy
  template:
    metadata:
      labels:
        app: hyperion-proxy
    spec:
      containers:
      - name: hyperion-proxy
        image: ghcr.io/hyperion-mc/hyperion/hyperion-proxy:latest
        args: ["--server", "tag.hyperion.svc.cluster.local:35565", "0.0.0.0:25565"]
        ports:
        - containerPort: 25565
        env:
        - name: RUST_LOG
          value: info
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hyperion-proxy
  namespace: hyperion
spec:
  selector:
    app: hyperion-proxy
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565 