name: Bench
on:
  pull_request_target:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  RUST_NIGHTLY_TOOLCHAIN: nightly-2024-12-18
  RUSTFLAGS: -Clinker=/usr/bin/clang -Clink-arg=--ld-path=/usr/local/bin/mold -Ctarget-cpu=native -Zshare-generics=y -Zthreads=0

jobs:
  export:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ general ]
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - name: Install cargo-export
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-export
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo export
        run: cargo export target/benchmarks -- bench --bench=${{ matrix.benchmark }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bench_${{ matrix.benchmark }}
          path: target/benchmarks/${{ matrix.benchmark }}

  compare:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ general ]
    permissions:
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Download base benchmark
        id: download
        uses: dawidd6/action-download-artifact@v7
        continue-on-error: true
        with:
          name: bench_${{ matrix.benchmark }}
          path: /tmp/bench/
          if_no_artifact_found: ignore
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_NIGHTLY_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo bench
        if: steps.download.outcome == 'success'
        run: cargo bench --bench=${{ matrix.benchmark }} -- compare /tmp/bench/${{ matrix.benchmark }} > bench_output_${{ matrix.benchmark }}.txt
      - name: remove /tmp/bench
        if: steps.download.outcome == 'success'
        run: rm -rf /tmp/bench
      - name: Post benchmark results as PR comment
        if: steps.download.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = `bench_output_${{ matrix.benchmark }}.txt`;
            const output = fs.readFileSync(path, 'utf8');
            
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### Benchmark Results for ${{ matrix.benchmark }}\n\`\`\`\n${output}\`\`\`\n\nComparing to main branch`,
            };
            await github.rest.issues.createComment(comment);