name: Nix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      
      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check Flake
        uses: DeterminateSystems/flake-checker-action@main
      
      - name: Run Nix Build
        run: nix build
      
      - name: Run Nix Flake Check
        run: nix flake check 